### ISSUE TITLE
Exceotion error when getting 10/28

### ISSUE THREAD

**Issue by tommycahir** [edit4ever/zap2xml#2]
I get the following error when running the script, it always seems to stop at the same position

2016-10-14 16:23:44,526 Getting: http://tvschedule.zap2it.com/tvlistings/ZCGrid.do?isDescriptionOn=true&fromTimeInMillis=1476637200000&aid=tvschedule
2016-10-14 16:23:47,315 Exception
2016-10-14 16:23:47,321 Traceback (most recent call last):
  File "zap2xml.py", line 1916, in main
    parseGrid(fn) #data read in and unicode it
  File "zap2xml.py", line 1082, in parseGrid
    p.feed(b)
  File "/usr/lib/python2.7/HTMLParser.py", line 117, in feed
  File "/usr/lib/python2.7/HTMLParser.py", line 161, in goahead
  File "/usr/lib/python2.7/HTMLParser.py", line 327, in parse_starttag
  File "zap2xml.py", line 704, in handle_starttag
    globals()['on_%s' % tag](self, tag, attrs)
  File "zap2xml.py", line 323, in on_td
    if re.search("^MV",cp):
  File "/usr/lib/python2.7/re.py", line 146, in search
TypeError: expected string or buffer

**Comment by tommycahir** [comment]
Edit4ever has commented on the following thread on the kodi.tv forum pointing out the issue, his latest updated code resolves the error..
http://forum.kodi.tv/showthread.php?tid=267022&pid=2437236#pid2437236
